sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -Ur requirements.txt
script:
  - __python=$(python3 --version 2>&1 | awk '{print substr($2, 0, 3)}')
  - tox -e "py${pyver//\.}-std"
